### ISSUE TITLE
problems with installation 

### ISSUE THREAD

**Issue by sourabhtk37** [EasyGnuPG/pgpg-ds#4]
While running `ds make`, I am getting segmentation fault on line 35 of ds on stdout, logs doesn't show this:
`/usr/bin/ds: line 35:  5997 Segmentation fault      ds create`

Also, after doing `ds inject install.sh`, I am getting `env: '/host/tmp/install.sh': No such file or directory`. 

OS: Debian GNU/Linux 9 (stretch)
Kernel: 4.12

**Comment by dashohoxha** [comment]
This problem comes out time after time, and almost always it is related to some problems on the host system. For example you don't have enough free space on disk, etc. So, try to make some common-sense checks, try to restart the docker service, try a reboot, etc.

**Comment by sourabhtk37** [comment]
Yup, I have the container running. But shouldn't the error/warning of seg fault be of concern. 

`ds inject install.sh` searches for setup.py file which is in `using-click` branch, therefore I was not able to test the branch. So doing `git clone --branch using-click https://github.com/easygnupg/pgpg` worked for me correctly.  

Closing this.
